name: build

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'v18'
        registry-url: 'https://registry.npmjs.org'
    - name: Deploy Info
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
